import disnake
from disnake.ext import commands
from cogs.config.variables import watermark,prefix,owner,ownername

class help(commands.Cog):
  def __init__(self, client):
    self.client = client

    print("Loading help module")

  #Bot Commands
  #help module
  @commands.command(name='help')
  @commands.cooldown(2,10,commands.BucketType.guild)
  async def helpmenu(self,ctx, arg= None):
    if arg == None:
      embed = disnake.Embed(title="Help on Bot", description="Module list", color=ctx.author.color)
      embed.add_field(name= f"{prefix}help utility", value="Sends help menu for utility cmds\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}help fun", value="Sends help menu for fun cmds\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}help music", value="Sends help menu for music cmds\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}help moderation", value="Sends help menu for moderation cmds\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      if ctx.author.id == owner:
        embed.add_field(name= f"{prefix}help owner", value="Sends help menu for bot-owner cmds\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))
      if ctx.message.author.guild_permissions.administrator:
        embed.add_field(name= f"{prefix}help secret", value="Sends help menu for Easter Egg cmds\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))
      embed.set_footer(text=f"{watermark} by {ownername}")
      await ctx.send (embed = embed)
    
    if arg == "owner":
      if ctx.author.id == owner:
        embed = disnake.Embed(title="Owner Commands", description="Command list", color=ctx.author.color)
        embed.add_field(name= f"{prefix}leave  <guildid>", value="Bot leaves from the mentioned guildid!\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name= f"{prefix}serverlist", value="Sends list of servers the bot is in and guildids!\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name= f"{prefix}toggle  <command_name>", value="Enables/Disabled a command!\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name= f"{prefix}loadcog  <cog_name>", value="Enables Cog\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name= f"{prefix}unloadcog  <cog_name>", value="Disables Cog\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name= f"{prefix}reloadcog  <cog_name>", value="Reloads Cog\n")
        embed.set_footer(text=f"{watermark} by {ownername}")
        await ctx.send(embed = embed)
      else:
        await ctx.send("``You dont have the permission to access this bot-owner only module!``")

    if arg == 'fun':
      embed = disnake.Embed(title="Fun commands", description="Command list", color=ctx.author.color)
      embed.add_field(name= f"{prefix}ai  <chat>", value="Use its ai-chat feature!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}cat", value="Sends cute catto pics!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}dog", value="Sends cute doggo pics!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}dadjoke", value="Sends Funny Dad Jokes lmao!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}meme", value="Sends dank memes!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}avatar  <mention>", value="Get avatar of mentioned user/bot!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}emojify  <text>", value="Turns text into emojis!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}ship <textname1>  <textname2>", value="Measures Love between names!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}8ball  <question>", value="Ask your questions to the mighty 8ball!\n")
      embed.set_footer(text=f"{watermark} by {ownername}")
      await ctx.send(embed = embed)

    if arg == 'utility':
      embed = disnake.Embed(title="Utility commands", description="Command list", color=ctx.author.color)
      embed.add_field(name= f"{prefix}memcount", value="Server Membercount\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}snipe", value="Snipes last deleted message in the channel!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}poll  <question>", value="Creates a poll with yes/no/notsure reactions!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}invite", value="Sends bot invite!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}support", value="Sends Support Server Invite!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}serverinfo", value="Sends Basic Server Info!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}remindme  <number><s/m/h/d>  <Task>", value=f"Set reminders for tasks! Eg: {prefix}remindme 2h I have exam! Only use one time quantity in one cmd!\n")
      embed.set_footer(text=f"{watermark} by {ownername}")
      await ctx.send(embed = embed)

    if arg == 'music':
      embed = disnake.Embed(title="Music commands", description="Command list", color=ctx.author.color)
      embed.add_field(name= f"{prefix}play  <song name>", value="Plays the song!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}pause", value="Pauses Playback\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}stop", value="Stops Playing and disconnects!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}join", value="Joins users vc\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}skip", value="Skips Playing Song\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}queue", value="Returns queue\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}playing", value="Returns current playing song!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}volume  <1-100>", value="Adjust volume!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}lyrics  <search term with author and music or each>", value="Get lyrics for any song!\n")
      
      embed.set_footer(text=f"{watermark} by {ownername}")
      await ctx.send(embed = embed)

    if arg == 'moderation':
      embed = disnake.Embed(title="Moderation commands", description="Command list", color=ctx.author.color)
      embed.add_field(name= f"{prefix}create-channel  <channel_name>", value="Creates channel\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}delete-channel  <channel_name>", value="Delete channel\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}sendmsg  <channelid>  <msg>", value="Sends message through the bot\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}purge  <amount>", value="Purges specified amount of messages!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}kick <mentionuser>  <reason>", value="Kicks the member!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}ban <mentionuser>  <reason>", value="Bans the member!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}unban <plain_text_username#discrim>", value="Unbans the member!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}mute <mentionuser>  <reason>", value="Mutes the member!\n")
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name = chr(173), value = chr(173))
      embed.add_field(name= f"{prefix}unmute <mentionuser>  <reason>", value="Unmutes the member!\n")
      embed.set_footer(text=f"{watermark} by {ownername}")
      await ctx.send(embed = embed)

    if arg == "secret":
      if ctx.message.author.guild_permissions.administrator or ctx.author.id == owner:
        embed = disnake.Embed(title="Secret Commands", description="Easter Eggs!", color=ctx.author.color)
        embed.add_field(name= f"{prefix}toko", value="A Toko Easter Egg\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))    
        embed.add_field(name= f"{prefix}douna", value="A Dounasiudb Easter Egg\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))    
        embed.add_field(name= f"{prefix}scotty", value="A Scotty Easter Egg\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))    
        embed.add_field(name= f"{prefix}fatrio", value="A Fatrio Easter Egg\n")
        embed.add_field(name = chr(173), value = chr(173))
        embed.add_field(name = chr(173), value = chr(173))    
        embed.add_field(name= f"{prefix}flouse", value="A Flouse Easter Egg\n")
        embed.set_footer(text=f"{watermark} by {ownername}")
        await ctx.send(embed = embed)
      else:
        await ctx.send("``You dont have the permission to access this admin only module!``")


  
def setup(client):
  client.add_cog(help(client))


